### ISSUE TITLE
Most title tags parse with unknown symbols

### ISSUE THREAD

**Issue by Max201** [shubhamjain/PHP-ID3#9]
I needs to parse title and artist from id3 of mp3. When i receive id3 array with your library, most of them has unknown symbols ( ? ). I was forced filter output with preg_replace('/[^a-z\-0-9]/i', '', $out) for receiving clear title of the track.

**Comment by rawzone** [comment]
I currently also have this problem after having retagged alot of MP3 files. It seems to be related to if the ID3 tags is written in UTF-8, UTF-16 or ISO-8859-1. (Not sure if the version of ID3 tag is also a thing of this).

I have tried to mb_convert_encoding the output, this removed the fact that the program broke, however I am back to having the unknown symbols in my output.

**Comment by Max201** [comment]
Thanks
